In [ ]:
import numpy as np

In [31]:
my_array = np.array([[1, 2, 3.0], [2, 2, 7]])
print(my_array)
print(type(my_array))

[[1. 2. 3.]
 [2. 2. 7.]]
<class 'numpy.ndarray'>


In [32]:
print(my_array.dtype)

float64


In [33]:
x = my_array.astype("int64")
print(x.dtype)

int64


In [34]:
print(my_array.shape)

(2, 3)


In [35]:
print(my_array.T)

[[1. 2.]
 [2. 2.]
 [3. 7.]]


In [37]:
print(my_array.reshape(1, -1))

[[1. 2. 3. 2. 2. 7.]]


In [41]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
print(np.random.randn(3, 4))

[[-1.03856266  0.78403608 -0.28997025 -1.17769214]
 [ 0.25469421  0.3996312  -0.48830223  0.65907868]
 [ 0.4886591   0.66062597  1.03477491  0.68730492]]


In [48]:
np.random.randint(0, 4, size=(2, 3))

array([[0, 2, 0],
       [3, 2, 3]])

In [51]:

a = np.random.randint(0, 4, size=(2, 3))
b = np.random.randint(0, 4, size=(2, 3))

print(a)
print('   -   ')
print(b)
print('  =  ')
print(a - b)

[[1 2 2]
 [2 1 1]]
   -   
[[3 2 2]
 [1 3 2]]
  =  
[[-2  0  0]
 [ 1 -2 -1]]


In [52]:
my_vector = np.array([1, 2, 3])

print(my_vector)
print('  +   ')
print(3)
print(' = ')
print(my_vector + 3)

[1 2 3]
  +   
3
 = 
[4 5 6]


In [56]:
my_matrix = np.random.randint(0, 3, size=(2, 3))
my_vector = np.array([1, 2, 3])
print(my_matrix)
print('  +  ')
print(my_vector)
print(' = ')
print(my_matrix + my_vector)

[[0 0 1]
 [2 1 1]]
  +  
[1 2 3]
 = 
[[1 2 4]
 [3 3 4]]


In [72]:
matrix_1 = np.random.randint(0, 3, size=(2, 3))
matrix_2 = np.random.randint(0, 3, size=(7, 2))

print(matrix_1)
print(' matrix multiply ')
print(matrix_2)
print(' = ')

print(np.matmul(matrix_1, matrix_2))


[[0 0 2]
 [2 0 1]]
 matrix multiply 
[[0 1]
 [2 1]
 [0 1]
 [0 2]
 [1 0]
 [1 0]
 [2 0]]
 = 


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 7 is different from 3)

In [61]:
matrix_1 @ matrix_2

array([[4, 1],
       [4, 3]])

In [62]:
np.sin(1)

0.8414709848078965

In [63]:
np.linalg.norm([3, 4])

5.0

In [69]:
print(my_matrix)
print(my_matrix[0, 1:4])

[[0 0 1]
 [2 1 1]]
[0 1]


In [71]:
np.array((2, 3), dtype="int64")

array([2, 3])